server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/v1/auth/**,/api/v1/user/**

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: secretkeyPasswordForAuth12312312312313213123123sdfsdf

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0