server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/queueDB
    username: user
    password: pass
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

smartqueue:
  kafka:
    topic: queue-event
    bootstrap-server: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 0.1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

#logging:
#  level:
#    org.apache.kafka: DEBUG
#    org.springframework.kafka: DEBUG
