server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/queueDB
    username: user
    password: pass
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

smartqueue:
  kafka:
    topic: queue-event
    bootstrap-server: localhost:9092
    consumer:
      group-id: worker-consumer